services:

  oracle_Db:
    image: oracle/database:21.3.0-xe
    volumes:
      - /home/develop/software/oracle/oradata:/opt/oracle/oradata
    ports:
      - 11521:1521
      - 15500:5500

  build_env:
    container_name: build_env
    build:
      dockerfile: corretto/Dockerfile
    ports:
      # ホスト側の18080ポートを、コンテナ側の8080ポートにマッピングする
      - 18080:8080
    tty: true
    volumes:
      - /home/develop/nextgen:/home/develop/nextgen

volumes:
  mysql_data:
